name: Minigame
version: '${project.version}'
main: me.megamagnum.main.Main
api-version: 1.19


commands:
  setup:
    description: Setup a minigame!
    permission: minigame.setup
    permission-message: No perms!!!!
  join:
    description: Join a starting minigame
  temp:
    description: temp
  kill:
    description: kill